CREATE TABLE IF NOT EXISTS `orders_2011_2` (
  `order_id` int(11) NOT NULL auto_increment,
  `CC_id` int(11) NOT NULL default '0',
  `order_type` int(11) NOT NULL default '0',
  `day_of_week` int(11) NOT NULL default '0',
  `order_month` int(11) NOT NULL default '0',
  `order_week` int(11) NOT NULL default '0',
  `total_amount` float NOT NULL default '0',
  `payment_type` int(11) NOT NULL default '0',
  `is_billable` char(1) NOT NULL default 'Y',
  `order_status` int(11) NOT NULL default '0',
  `date_cancel_from` date NOT NULL default '0000-00-00',
  `date_cancel_till` date NOT NULL default '0000-00-00',
  `storeroom_id` int(11) NOT NULL default '0',
  `user_id` int(11) NOT NULL default '0',
  `community` varchar(50) NOT NULL default '',
  `community_id` int(11) NOT NULL default '0',
  `note` varchar(64) NOT NULL default '',
  `handling_charge` float NOT NULL default '0',
  `order_reference` varchar(30) NOT NULL default '',
  `order_date` date NOT NULL default '0000-00-00',
  `advance_paid` float NOT NULL default '0',
  `is_debit_invoice` char(1) NOT NULL default 'N',
  `discount` smallint(6) NOT NULL default '0',
  `handling_is_percentage` char(1) NOT NULL default 'Y',
  `courier_charge` float NOT NULL default '0',
  `courier_is_percentage` char(1) NOT NULL default 'Y',
  `reseller_order_id` int(11) NOT NULL default '0',
  `is_modified` char(1) NOT NULL default 'N',
  PRIMARY KEY  (`order_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2256 ;